// packages/react/packages/dialog/Frame.tsx
import { getTransformStyleString } from 'bam-utility-plugins';
import { Dialog, Frame, OpenFrameOptions } from '@core/packages';
import { getClassNames as css } from '@core/style';
import { createVNode, isFrame, useFrame } from './utils';
import { useLayoutEffect, useState } from 'react';

interface FrameProps {
  dialog: Dialog;
  frame: Frame | OpenFrameOptions;
  zIndex?: number;
  children?: any;
}

export default (props: FrameProps) => {
  // { dialog, frame, zIndex }

  const [frame] = useState(() => {
    if (isFrame(props.frame)) {
      return props.frame;
    } else {
      const id = Symbol(props.frame?.name || 'Frame');
      props.dialog.openFrame(() => props.children, {
        ...props.frame,
        id,
      });
      return useFrame(id);
    }
  });

  const [init, setInit] = useState(false);
  const [dialog] = useState(props.dialog);
  const [width, setWidth] = useState(frame.width);
  const [height, setHeight] = useState(frame.height);
  const [top, setTop] = useState(frame.top);
  const [left, setLeft] = useState(frame.left);
  const View = createVNode(frame);

  /**
   * @Lifecycle
   */
  const onMount = () => {
    frame.onMount();
    if (dialog.isBackgroundMask && frame.hook.bgclick.length === 0) {
      frame.on('bgclick', () => frame.onClose());
    }
    frame.on('update', () => {
      setWidth(frame.width);
      setHeight(frame.height);
      setTop(frame.top);
      setLeft(frame.left);
    });
  };
  const onUnmount = () => {
    frame.onUnmount();
  };

  useLayoutEffect(() => {
    if (frame.element) {
      if (!init) {
        onMount();
        setInit(true);
      }
    } else {
      onUnmount();
    }
  });
  const zIndex = props.zIndex || 0;

  return (
    <div
      ref={(e) => frame.setFrameElement(e)}
      className={css().dialog_frame}
      style={{
        zIndex: zIndex + 1,
        transform: getTransformStyleString({
          translateX: frame.isFull ? '0' : left,
          translateY: frame.isFull ? '0' : top,
        }),
        width: frame.isFull ? '100vw' : width,
        height: frame.isFull ? '100vh' : height,
      }}
      onClick={(e) => e.stopPropagation()}
      onMouseDown={() => dialog.sortToRight(frame.id)}
    >
      {View}
    </div>
  );
};

// src/packages/dialog/vue/Frame.tsx
import { onMounted, onUpdated, onUnmounted, computed, defineComponent, getCurrentInstance } from 'vue';
import type { DefineComponent, PropType } from 'vue';
import Dialog from '../core/dialog';
import Frame from '../core/frame';
import { getFrameData, getFrameMethods } from '../core/interface';
import { getTransformStyleString } from 'bam-utility-plugins';
import css from '/@/style';

export default defineComponent({
  name: 'bam-frame',
  props: {
    dialog: {
      type: Object as PropType<Dialog>,
      required: true,
    },
    view: {
      type: Object as PropType<DefineComponent>,
      required: true,
    },
    frame: {
      type: Object as PropType<Frame>,
      required: true,
    },
    zIndex: {
      type: Number,
      default: 0,
    },
  },

  setup(props, { expose }) {
    const instance = getCurrentInstance();

    /**
     * @Data
     */
    expose({});

    /**
     * @Created
     */
    if (props.dialog.isBackgroundMask && props.frame.hook.bgclick.length === 0) {
      props.frame.on('bgclick', () => props.frame.onClose());
    }

    /**
     * @Computed
     */
    const frameData = computed(() => getFrameData(props.frame));
    const frameMethods = computed(() => getFrameMethods(props.frame));

    /**
     * @Event
     */

    /**
     * @Lifecycle
     */
    onMounted(() => props.frame.onMount(instance));
    onUpdated(() => props.frame.onUpdate(instance));
    onUnmounted(() => props.frame.onUnmount(instance));

    /**
     * @Render
     */
    const View = props.view;
    return () => (
      <div
        ref={(e: Element) => props.frame.setFrameElement(e)}
        class={css.dialog_frame}
        style={{
          zIndex: props.zIndex,
          transform: getTransformStyleString({
            translateX: props.frame.isFull ? '0' : props.frame.left,
            translateY: props.frame.isFull ? '0' : props.frame.top,
          }),
          width: props.frame.isFull ? '100vw' : props.frame.width,
          height: props.frame.isFull ? '100vh' : props.frame.height,
        }}
        onClick={(e) => e.stopPropagation()}
        onMousedown={() => props.dialog.sortToRight(props.frame.id)}
      >
        <View
          class={css.dialog_view}
          frame-data={frameData.value}
          frame-methods={frameMethods.value}
          frame-props={props.frame.props}
        />
      </div>
    );
  },
});
